### ISSUE TITLE
Error running main script as described in the README

### ISSUE THREAD

**Issue by ashermancinelli** [sambritton/Max_Entropy_Python#3]
When running as described in the readme I get this result:
```bash
> python ./GLYCOLYSIS_TCA_GOGAT_FUNCTION.py 1 4 0 1e-06 0.05 2
['./GLYCOLYSIS_TCA_GOGAT_FUNCTION.py', '1', '4', '0', '1e-06', '0.05', '2']
./GLYCOLYSIS_TCA_GOGAT_FUNCTION.py 1 4 0 1e-06 0.05 2
The total numbers of args passed to the script: 7 
Args list: ['./GLYCOLYSIS_TCA_GOGAT_FUNCTION.py', '1', '4', '0', '1e-06', '0.05', '2'] 
Script name: ./GLYCOLYSIS_TCA_GOGAT_FUNCTION.py
Argument # 0 : ./GLYCOLYSIS_TCA_GOGAT_FUNCTION.py
Argument # 1 : 1
Argument # 2 : 4
Argument # 3 : 0
Argument # 4 : 1e-06
Argument # 5 : 0.05
Argument # 6 : 2
sim
1
n_back_step
4
using experimental metabolite data
False
learning_rate
1e-06
epsilon
0.05
eps_threshold
2.0
gamma
0.9
/qfs/people/manc568/projects/Max_Entropy_Python/Basic_Functions/max_entropy_functions.py:96: RuntimeWarning: overflow encountered in exp
  EKQ = np.exp(log_EKQ)
Traceback (most recent call last):
  File "./GLYCOLYSIS_TCA_GOGAT_FUNCTION.py", line 698, in <module>
    run(sys.argv[:])
  File "./GLYCOLYSIS_TCA_GOGAT_FUNCTION.py", line 447, in run
    reaction_choice = max_entropy_functions.get_enzyme2regulate(ipolicy, delta_S_metab, ccc, KQ_f, E_regulation, res_lsq1.x)                                                        
TypeError: get_enzyme2regulate() missing 1 required positional argument: 'v_counts'
```
@sambritton Any idea why I'm getting this issue?

**Comment by sambritton** [comment]
I removed the test function call 'get_enzyme2regulate' and re-uploaded a file that worked.

**Comment by ashermancinelli** [comment]
@sambritton Thanks!
